input_cameras:
    - name: "Logitech"
      path: "/dev/video0"
      width: 640
      height: 480
      buffer_count: 2
    # - name: "Old"
    #   path: "/dev/video0"
    #   width: 1500
    #   height: 1000
    #   buffer_count: 4

output_cameras:
    - name: "VirtualCamera"
      path: "/dev/video8"
      width: 640
      height: 480
      jpeg_quality: 90
      subsampling: "444"  # Options: 444, 422, 420, gray, 440, 411

external_data:
    media_folder_path: "../media"
    models_folder_path: "../models"
    preload_content: true
    WFLW_folder_path: "../WFLW"

window:
    title: "LinuxFace"
    width: 640
    height: 480

enable_gpu: true
